# Translations template for cinder.
# Copyright (C) 2016 ORGANIZATION
# This file is distributed under the same license as the cinder project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: cinder 8.0.1.dev115\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-04-18 07:12+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.2.0\n"

#: cinder/context.py:205
msgid "Unable to get internal tenant context: Missing required config parameters."
msgstr ""

#: cinder/coordination.py:171
#, python-format
msgid "Reconnect attempt %(attempt)s failed. Next try in %(backoff).2fs."
msgstr ""

#: cinder/quota_utils.py:86
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG volume - "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/quota_utils.py:97 cinder/transfer/api.py:201
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create volume (%(d_consumed)d "
"volumes already consumed)"
msgstr ""

#: cinder/service.py:95
msgid ""
"OSProfiler is enabled.\n"
"It means that person who knows any of hmac_keys that are specified in "
"/etc/cinder/cinder.conf can trace his requests. \n"
"In real life only operator can read this file so there is no security "
"issue. Note that even if person can trigger profiler, only admin user can"
" retrieve trace information.\n"
"To disable OSprofiler set in cinder.conf:\n"
"[profiler]\n"
"enabled=false"
msgstr ""

#: cinder/service.py:200
#, python-format
msgid ""
"Report interval must be less than service down time. Current config "
"service_down_time: %(service_down_time)s, report_interval for this: "
"service is: %(report_interval)s. Setting global service_down_time to: "
"%(new_down_time)s"
msgstr ""

#: cinder/utils.py:960
#, python-format
msgid "Invalid trace flag: %s"
msgstr ""

#: cinder/api/__init__.py:31
msgid ""
"The v1 api is deprecated and is not under active development. You should "
"set enable_v1_api=false and enable_v3_api=true in your cinder.conf file."
msgstr ""

#: cinder/api/extensions.py:276
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr ""

#: cinder/api/extensions.py:345
#, python-format
msgid "Failed to load extension %(classpath)s: %(exc)s"
msgstr ""

#: cinder/api/extensions.py:370
#, python-format
msgid "Failed to load extension %(ext_name)s: %(exc)s"
msgstr ""

#: cinder/api/openstack/__init__.py:114
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: cinder/backup/api.py:292
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG backup "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/backup/api.py:304
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create backups (%(d_consumed)d "
"backups already consumed)"
msgstr ""

#: cinder/backup/chunkeddriver.py:725
msgid "Error while listing objects, continuing with delete."
msgstr ""

#: cinder/backup/driver.py:236
msgid ""
"Destination volume type is different from source volume type for an "
"encrypted volume. Encrypted backup restore has failed."
msgstr ""

#: cinder/backup/manager.py:693
#, python-format
msgid ""
"Backup service %(service)s does not support verify. Backup id %(id)s is "
"not verified. Skipping verify."
msgstr ""

#: cinder/backup/manager.py:830
#, python-format
msgid ""
"Failed to terminate the connection of volume %(volume_id)s, but it is "
"acceptable."
msgstr ""

#: cinder/backup/drivers/ceph.py:1172
#, python-format
msgid ""
"RBD image for backup %(backup)s of volume %(volume)s not found. Deleting "
"backup metadata."
msgstr ""

#: cinder/common/sqlalchemyutils.py:68
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: cinder/consistencygroup/api.py:111
#, python-format
msgid "Availability zone '%s' is invalid"
msgstr ""

#: cinder/db/sqlalchemy/api.py:121
msgid "Use of empty request context is deprecated"
msgstr ""

#: cinder/db/sqlalchemy/api.py:233
#, python-format
msgid "Deadlock detected when running '%(func_name)s': Retrying..."
msgstr ""

#: cinder/db/sqlalchemy/api.py:1009
#, python-format
msgid "Change will make usage less than 0 for the following resources: %s"
msgstr ""

#: cinder/image/cache.py:168
#, python-format
msgid "Image-volume cache for host %(host)s does not have enough space (GB)."
msgstr ""

#: cinder/image/glance.py:161
msgid ""
"glance_num_retries shouldn't be a negative value. The number of retries "
"will be set to 0 until this iscorrected in the cinder.conf."
msgstr ""

#: cinder/image/image_utils.py:72
msgid "qemu-img is not installed."
msgstr ""

#: cinder/keymgr/conf_key_mgr.py:80
msgid ""
"config option keymgr.fixed_key has not been defined: some operations may "
"fail unexpectedly"
msgstr ""

#: cinder/keymgr/conf_key_mgr.py:136
#, python-format
msgid "Not deleting key %s"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:427
#, python-format
msgid "No weighed hosts found for volume with properties: %s"
msgstr ""

#: cinder/scheduler/host_manager.py:463
#, python-format
msgid "volume service is down. (host: %s)"
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:71
#, python-format
msgid ""
"Insufficient free space for volume creation. Total capacity is "
"%(total).2f on host %(host)s."
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:93
#, python-format
msgid ""
"Insufficient free space for thin provisioning. The ratio of provisioned "
"capacity over total capacity %(provisioned_ratio).2f has exceeded the "
"maximum over subscription ratio %(oversub_ratio).2f on host %(host)s."
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:114
#, python-format
msgid ""
"Filtering out host %(host)s with an invalid maximum over subscription "
"ratio of %(oversub_ratio).2f. The ratio should be a minimum of 1.0."
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:124
#, python-format
msgid ""
"Insufficient free space for volume creation on host %(host)s (requested /"
" avail): %(requested)s/%(available)s"
msgstr ""

#: cinder/scheduler/filters/driver_filter.py:61
#, python-format
msgid "Error in filtering function '%(function)s' : '%(error)s' :: failing host"
msgstr ""

#: cinder/scheduler/filters/instance_locality_filter.py:99
#, python-format
msgid "Hint \"%s\" dropped because ExtendedServerAttributes not active in Nova."
msgstr ""

#: cinder/scheduler/filters/instance_locality_filter.py:110
#, python-format
msgid ""
"Hint \"%s\" dropped because Nova did not return enough information. "
"Either Nova policy needs to be changed or a privileged account for Nova "
"should be specified in conf."
msgstr ""

#: cinder/scheduler/weights/goodness.py:59
msgid "Goodness function not set :: defaulting to minimal goodness rating of 0"
msgstr ""

#: cinder/scheduler/weights/goodness.py:67
#, python-format
msgid ""
"Error in goodness_function function '%(function)s' : '%(error)s' :: "
"Defaulting to a goodness of 0"
msgstr ""

#: cinder/scheduler/weights/goodness.py:78
#, python-format
msgid ""
"Invalid goodness result.  Result must be between 0 and 100.  Result "
"generated: '%s' :: Defaulting to a goodness of 0"
msgstr ""

#: cinder/tests/unit/volume/drivers/netapp/dataontap/test_block_base.py:87
#: cinder/volume/drivers/netapp/dataontap/block_base.py:133
#, python-format
msgid ""
"The \"netapp_size_multiplier\" configuration option is deprecated and "
"will be removed in the Mitaka release. Please set \"reserved_percentage ="
" %d\" instead."
msgstr ""

#: cinder/transfer/api.py:189 cinder/volume/flows/api/create_volume.py:622
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG volume "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/volume/api.py:428
#, python-format
msgid "Unable to delete encryption key for volume: %s."
msgstr ""

#: cinder/volume/api.py:760 cinder/volume/utils.py:721
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG snapshot "
"(%(d_consumed)dG of %(d_quota)dG already consumed)."
msgstr ""

#: cinder/volume/api.py:772 cinder/volume/utils.py:733
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create snapshot (%(d_consumed)d "
"snapshots already consumed)."
msgstr ""

#: cinder/volume/driver.py:470
#, python-format
msgid "Failed to activate volume copy throttling: %(err)s"
msgstr ""

#: cinder/volume/driver.py:675
#, python-format
msgid ""
"The colon in vendor name was replaced by underscore. Updated vendor name "
"is %(name)s\"."
msgstr ""

#: cinder/volume/driver.py:689
#, python-format
msgid ""
"Vendor unique property \"%(property)s\" must start with vendor prefix "
"with colon \"%(prefix)s\". The property was not registered on "
"capabilities list."
msgstr ""

#: cinder/volume/driver.py:867
#, python-format
msgid ""
"Failed terminating the connection of volume %(volume_id)s, but it is "
"acceptable."
msgstr ""

#: cinder/volume/driver.py:2342 cinder/volume/targets/iscsi.py:154
msgid "ISCSI provider_location not stored, using discovery"
msgstr ""

#: cinder/volume/manager.py:246
#, python-format
msgid "Driver path %s is deprecated, update your configuration to the new path."
msgstr ""

#: cinder/volume/manager.py:272
msgid "Suppressing requests library SSL Warnings"
msgstr ""

#: cinder/volume/manager.py:462
#, python-format
msgid "Detected volume stuck in %(curr_status)s status, setting to ERROR."
msgstr ""

#: cinder/volume/manager.py:481
msgid "Detected snapshot stuck in creating status, setting to ERROR."
msgstr ""

#: cinder/volume/manager.py:1147
#, python-format
msgid ""
"Unable to ensure space for image-volume in cache. Will skip creating "
"entry for image %(image)s on host %(host)s."
msgstr ""

#: cinder/volume/manager.py:1157
#, python-format
msgid ""
"Unable to clone image_volume for image %(image_id)s will not create cache"
" entry."
msgstr ""

#: cinder/volume/manager.py:1169
#, python-format
msgid "Failed to create new image-volume cache entry. Error: %(exception)s"
msgstr ""

#: cinder/volume/manager.py:1259
#, python-format
msgid "Registration of image volume URI %(uri)s to image %(image_id)s failed."
msgstr ""

#: cinder/volume/manager.py:1332
#, python-format
msgid "Deleting image in unexpected status: %(image_status)s."
msgstr ""

#: cinder/volume/manager.py:1338
msgid "Image delete encountered an error."
msgstr ""

#: cinder/volume/manager.py:1826
#, python-format
msgid ""
"Failed to migrate volume. The destination volume %(vol)s is not deleted "
"since the source volume may have been deleted."
msgstr ""

#: cinder/volume/manager.py:1995
#, python-format
msgid "Update driver status failed: %(config_group)s is uninitialized."
msgstr ""

#: cinder/volume/manager.py:3385
msgid ""
"Error encountered on Cinder backend during freeze operation, service is "
"frozen, however notification to driver has failed."
msgstr ""

#: cinder/volume/qos_specs.py:201
#, python-format
msgid "Failed to associate qos specs %(id)s with type: %(vol_type_id)s"
msgstr ""

#: cinder/volume/qos_specs.py:215
#, python-format
msgid "Failed to disassociate qos specs %(id)s with type: %(vol_type_id)s"
msgstr ""

#: cinder/volume/qos_specs.py:229
#, python-format
msgid "Failed to disassociate qos specs %s."
msgstr ""

#: cinder/volume/throttling.py:88
#, python-format
msgid "Failed to setup blkio cgroup to throttle the device '%(device)s'."
msgstr ""

#: cinder/volume/utils.py:284
#, python-format
msgid ""
"Incorrect value error: %(blocksize)s, it may indicate that "
"'volume_dd_blocksize' was configured incorrectly. Fall back to default."
msgstr ""

#: cinder/volume/utils.py:708
#, python-format
msgid "Error encountered translating config_string: %(config_string)s to dict"
msgstr ""

#: cinder/volume/drivers/block_device.py:97
#, python-format
msgid "The device %s won't be cleared."
msgstr ""

#: cinder/volume/drivers/drbdmanagedrv.py:169
#, python-format
msgid "Got disconnected; trying to reconnect. (%s)"
msgstr ""

#: cinder/volume/drivers/drbdmanagedrv.py:329
#, python-format
msgid ""
"Try #%(try)d: Volume \"%(res)s\"/%(vol)d not yet deployed on "
"\"%(host)s\", waiting."
msgstr ""

#: cinder/volume/drivers/drbdmanagedrv.py:718
#, python-format
msgid "snapshot: %s not found, skipping delete operation"
msgstr ""

#: cinder/volume/drivers/eqlx.py:168
msgid ""
"Configuration options eqlx_use_chap, eqlx_chap_login and "
"eqlx_chap_password are deprecated. Use use_chap_auth, chap_username and "
"chap_password respectively for the same."
msgstr ""

#: cinder/volume/drivers/eqlx.py:182
msgid ""
"Configuration option eqlx_cli_timeout is deprecated and will be removed "
"in M release. Use ssh_conn_timeout instead."
msgstr ""

#: cinder/volume/drivers/eqlx.py:462
#, python-format
msgid "Volume %s was not found while trying to delete it."
msgstr ""

#: cinder/volume/drivers/eqlx.py:582
#, python-format
msgid "Volume %s is not found!, it may have been deleted."
msgstr ""

#: cinder/volume/drivers/glusterfs.py:113
#, python-format
msgid "Exception during unmounting %s"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:133
#, python-format
msgid "Failed to refresh mounts, reason=%s"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:241 cinder/volume/drivers/quobyte.py:225
#: cinder/volume/drivers/remotefs.py:282
#, python-format
msgid "Volume %s does not have provider_location specified, skipping"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:350
msgid ""
"Fallocate not supported by current version of glusterfs. So falling back "
"to dd."
msgstr ""

#: cinder/volume/drivers/hgst.py:344
msgid "Unable to poll cluster free space."
msgstr ""

#: cinder/volume/drivers/hgst.py:410
#, python-format
msgid "Unable to delete space %(space)s"
msgstr ""

#: cinder/volume/drivers/hgst.py:415
msgid "Attempted to delete a space that's not there."
msgstr ""

#: cinder/volume/drivers/lvm.py:191
#, python-format
msgid "Unable to update stats on non-initialized Volume Group: %s"
msgstr ""

#: cinder/volume/drivers/lvm.py:435
#, python-format
msgid "snapshot: %s not found, skipping delete operations"
msgstr ""

#: cinder/volume/drivers/nfs.py:353 cinder/volume/drivers/remotefs.py:569
#, python-format
msgid ""
"The NAS file permissions mode will be 666 (allowing other/world read & "
"write access). This is considered an insecure NAS environment. Please see"
" %s for information on a secure NFS configuration."
msgstr ""

#: cinder/volume/drivers/nfs.py:374 cinder/volume/drivers/remotefs.py:562
#, python-format
msgid ""
"The NAS file operations will be run as root: allowing root level access "
"at the storage backend. This is considered an insecure NAS environment. "
"Please see %s for information on a secure NAS configuration."
msgstr ""

#: cinder/volume/drivers/nimble.py:172
#, python-format
msgid "Error updating agent-type for volume %s."
msgstr ""

#: cinder/volume/drivers/pure.py:320
#, python-format
msgid "Adding Volume to Protection Group failed with message: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:371
#, python-format
msgid "Volume deletion failed with message: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:402
#, python-format
msgid "Unable to delete snapshot, assuming already deleted. Error: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:470
#, python-format
msgid "Purity host deletion failed: %(msg)s."
msgstr ""

#: cinder/volume/drivers/pure.py:692
#, python-format
msgid "Unable to delete Protection Group: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:765
#, python-format
msgid "Unable to delete Protection Group Snapshot: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:882
#, python-format
msgid "Unable to rename %(old_name)s, error message: %(error)s"
msgstr ""

#: cinder/volume/drivers/pure.py:1125
#, python-format
msgid "Disable replication on volume failed: already disabled: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:1389
#, python-format
msgid "Skipping creation of PG %s since it already exists."
msgstr ""

#: cinder/volume/drivers/pure.py:1397
#, python-format
msgid "Protection group %s is deleted but not eradicated - will recreate."
msgstr ""

#: cinder/volume/drivers/quobyte.py:148
msgid ""
"The NAS file operations will be run as root, allowing root level access "
"at the storage backend."
msgstr ""

#: cinder/volume/drivers/quobyte.py:160
msgid ""
"The NAS file permissions mode will be 666 (allowing other/world read & "
"write access)."
msgstr ""

#: cinder/volume/drivers/quobyte.py:372
#, python-format
msgid "Exception during mounting %s"
msgstr ""

#: cinder/volume/drivers/quobyte.py:432
#, python-format
msgid "Failed to unmount previous mount: %s"
msgstr ""

#: cinder/volume/drivers/quobyte.py:436
#, python-format
msgid "Unknown error occurred while checking mount point: %s Trying to continue."
msgstr ""

#: cinder/volume/drivers/quobyte.py:455
#, python-format
msgid "%s is already mounted"
msgstr ""

#: cinder/volume/drivers/quobyte.py:474
#, python-format
msgid "Volume is not writable. Please broaden the file permissions. Mount: %s"
msgstr ""

#: cinder/volume/drivers/rbd.py:184
msgid "flush() not supported in this version of librbd"
msgstr ""

#: cinder/volume/drivers/rbd.py:401
msgid "Unable to get rados pool stats."
msgstr ""

#: cinder/volume/drivers/rbd.py:916
msgid "volume_tmp_dir is now deprecated, please use image_conversion_dir."
msgstr ""

#: cinder/volume/drivers/remotefs.py:367
#, python-format
msgid "%(path)s is being set with open permissions: %(perm)s"
msgstr ""

#: cinder/volume/drivers/remotefs.py:979
#, python-format
msgid "No backing file found for %s, allowing snapshot to be deleted."
msgstr ""

#: cinder/volume/drivers/sheepdog.py:196
#, python-format
msgid "Volume not found. %s"
msgstr ""

#: cinder/volume/drivers/sheepdog.py:227
#, python-format
msgid "Snapshot \"%s\" not found."
msgstr ""

#: cinder/volume/drivers/sheepdog.py:229
#, python-format
msgid "Volume \"%s\" not found."
msgstr ""

#: cinder/volume/drivers/smbfs.py:305
#, python-format
msgid "Volume %s does not have provider_location specified, skipping."
msgstr ""

#: cinder/volume/drivers/solidfire.py:620
#, python-format
msgid "More than one valid preset was detected, using %s"
msgstr ""

#: cinder/volume/drivers/solidfire.py:1059
msgid "Requested image is not accessible by current Tenant."
msgstr ""

#: cinder/volume/drivers/tegile.py:376
#, python-format
msgid ""
"TegileIntelliFlashVolumeDriver(%(clsname)s) _update_volume_stats failed: "
"%(error)s"
msgstr ""

#: cinder/volume/drivers/tintri.py:391
#, python-format
msgid "Exception while creating image %(image_id)s snapshot. Exception: %(exc)s"
msgstr ""

#: cinder/volume/drivers/tintri.py:416
#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:452
#, python-format
msgid "Exception during deleting %s"
msgstr ""

#: cinder/volume/drivers/tintri.py:425
#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:765
#, python-format
msgid "Destination %s already exists."
msgstr ""

#: cinder/volume/drivers/tintri.py:433
#, python-format
msgid "Exception moving file %(src)s. Message: %(e)s"
msgstr ""

#: cinder/volume/drivers/tintri.py:498
#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:511
#, python-format
msgid "Unexpected exception during image cloning in share %s"
msgstr ""

#: cinder/volume/drivers/tintri.py:613
msgid "Unexpected exception while listing used share."
msgstr ""

#: cinder/volume/drivers/xio.py:462
#, python-format
msgid "IOnetworks GET failed (%d)"
msgstr ""

#: cinder/volume/drivers/xio.py:587
#, python-format
msgid "Could not get status for %(name)s (%(status)d)."
msgstr ""

#: cinder/volume/drivers/xio.py:594
msgid "No volume node in XML content."
msgstr ""

#: cinder/volume/drivers/xio.py:601
#, python-format
msgid "No status payload for volume %s."
msgstr ""

#: cinder/volume/drivers/xio.py:688
#, python-format
msgid "Volume %(name)s already presented (%(status)d)!"
msgstr ""

#: cinder/volume/drivers/xio.py:956
#, python-format
msgid "Could not get pool information (%s)!"
msgstr ""

#: cinder/volume/drivers/xio.py:1191
#, python-format
msgid "%s not found!"
msgstr ""

#: cinder/volume/drivers/xio.py:1202
#, python-format
msgid "DELETE call failed for %s!"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:670
#, python-format
msgid "Volume %s initialization failure."
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:840
#: cinder/volume/drivers/dell/dell_storagecenter_api.py:2340
#, python-format
msgid "Unable to create folder %s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:1031
#, python-format
msgid "delete_volume: unable to find volume provider_id: %s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:1099
#, python-format
msgid "Unable to find appropriate OS %s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:1361
msgid "Inconsistent Luns."
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:1366
msgid "_find_wwn: serverhba is None."
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:1368
msgid "_find_wwn: Unable to find port wwn."
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:1370
msgid "_find_wwn: controllerport is None."
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:1715
#, python-format
msgid "Unable to create snapshot %s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:1752
#, python-format
msgid "Unable to find snapshot %s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_api.py:2521
#, python-format
msgid "Unable to locate replication %(vol)s to %(ssn)s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_common.py:305
#, python-format
msgid "Unable to delete replication of Volume %(vname)s to Storage Center %(sc)s."
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_common.py:353
#, python-format
msgid "Unable to locate volume:%s"
msgstr ""

#: cinder/volume/drivers/dell/dell_storagecenter_common.py:1035
#, python-format
msgid "SSN %s appears to be down."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:747
msgid ""
"The VMAX plugin only supports Retype. If a pool based migration is "
"necessary this will happen on a Retype From the command line: cinder "
"--os-volume-api-version 2 retype <volumeId> <volumeType> --migration-"
"policy on-demand"
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:784
#, python-format
msgid ""
"Failed to migrate: %(volumeName)s from default source storage group for "
"FAST policy: %(sourceFastPolicyName)s. Attempting cleanup... "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:812
#, python-format
msgid ""
"Attempting a rollback of: %(volumeName)s to original pool "
"%(sourcePoolInstanceName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:844
#, python-format
msgid "_migrate_rollback on : %(volumeName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:880
#, python-format
msgid "_migrate_cleanup on : %(volumeName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:1077
#, python-format
msgid ""
"The volume: %(volumename)s was not first part of the default storage "
"group for FAST policy %(fastPolicyName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:1170
#, python-format
msgid "Volume: %(volumeName)s is not currently belonging to any storage group."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:1539
#, python-format
msgid ""
"Volume is masked but not to host %(host)s as expected. Returning empty "
"dictionary."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:2219
#, python-format
msgid ""
"Pre check for deletion. Volume: %(volumeName)s is part of a storage "
"group. Attempting removal from %(storageGroupInstanceNames)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:3095
#, python-format
msgid "Volume : %(volumeName)s is not currently belonging to any storage group."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:3368
#, python-format
msgid ""
"The volume: %(volumename)s. was not first part of the default storage "
"group for FAST policy %(fastPolicyName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:3801
#, python-format
msgid ""
"Clone failed on V3. Cleaning up the target volume. Clone name: "
"%(cloneName)s "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:4015
#, python-format
msgid "FAST is enabled. Policy: %(fastPolicyName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_fast.py:140
#, python-format
msgid "Volume: %(volumeName)s Does not belong to storage group %(defaultSgName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_fast.py:411
msgid "Unable to get storage tiers from tier policy rule."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_fc.py:263
#, python-format
msgid "Volume %(volume)s is not in any masking view."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:209
#, python-format
msgid ""
"Volume: %(volumeName)s does not belong to storage group "
"%(defaultSgGroupName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:522
#, python-format
msgid "Volume: %(volumeName)s is already part of storage group %(sgGroupName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1123
#: cinder/volume/drivers/emc/emc_vmax_masking.py:1390
#, python-format
msgid "Unable to find Masking view: %(view)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1292
#, python-format
msgid ""
"No storage group found. Performing rollback on Volume: %(volumeName)s To "
"return it to the default storage group for FAST policy "
"%(fastPolicyName)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1672
#, python-format
msgid ""
"Volume %(volumeName)s was not first part of the default storage group for"
" the FAST Policy."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1819
#, python-format
msgid "Volume %(volumeName)s is belong to %(sgNum)s storage groups."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:2239
#, python-format
msgid "No target ports found in masking view %(maskingView)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:2309
#, python-format
msgid "No port group found in masking view %(mv)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:2328
#, python-format
msgid "No Initiator group found in masking view %(mv)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:2528
#, python-format
msgid "Deletion of initiator path %(hardwareIdPath)s is failed."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:2601
#, python-format
msgid ""
"Initiator group %(initiatorGroupName)s is associated with masking views "
"and can't be deleted. Number of associated masking view is: %(nmv)d."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_provision_v3.py:709
#, python-format
msgid ""
"Remaining capacity %(remainingCapacityGb)s GBs is determined from SRP "
"pool capacity and not the SLO capacity. Performance may not be what you "
"expect."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_utils.py:1245
#, python-format
msgid "Storage sync name not found for target %(target)s on %(storageSystem)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_utils.py:1286
#, python-format
msgid ""
"Group sync name not found for target group %(target)s on "
"%(storageSystem)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_utils.py:1741
#, python-format
msgid ""
"CreateStorageHardwareID failed. initiator: %(initiator)s, rc=%(rc)d, "
"ret=%(ret)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_utils.py:1761
msgid "Cannot determine the hardware type."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:715
msgid "san_secondary_ip is configured as the same value as san_ip."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:821
#, python-format
msgid "LUN already exists, LUN name %(name)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:875
#, python-format
msgid "LUN is already deleted, LUN name %(name)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:949
#, python-format
msgid "LUN %(name)s is already expanded. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1005
#, python-format
msgid "Consistency group %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1089
#, python-format
msgid "CG %(cg_name)s does not exist. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1093
#, python-format
msgid "CG %(cg_name)s is deleting. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1115
#, python-format
msgid "Cgsnapshot name %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1144
#, python-format
msgid "Snapshot %(name)s for consistency group does not exist. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1163
#: cinder/volume/drivers/emc/emc_vnx_cli.py:1183
#, python-format
msgid "Snapshot %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1200
#, python-format
msgid "Snapshot %(name)s may deleted already. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1207
#, python-format
msgid "Snapshot %(name)s is in use, retry. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1234
#, python-format
msgid "Mount point %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1261
#, python-format
msgid ""
"Snapshot %(snapname)s is attached to snapshot mount point %(mpname)s "
"already. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1281
#, python-format
msgid "The specified Snapshot mount point %s is not currently attached."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1321
#, python-format
msgid ""
"Starting migration from %(src)s to %(dst)s failed. Will check whether "
"migration was successful later.: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1403
#, python-format
msgid "Start migration failed. Message: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1406
#, python-format
msgid "Deleting temp LUN after migration start failed. LUN: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1496
#, python-format
msgid "Storage group %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1512
#, python-format
msgid ""
"Storage group %(name)s doesn't exist, may have already been deleted. "
"Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1542
#, python-format
msgid ""
"Host %(host)s has already disconnected from storage group %(sgname)s. "
"Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1579
#, python-format
msgid "HLU %(hlu)s has already been removed from %(sgname)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1755
msgid "No array serial number returned, set as unknown."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1789
#, python-format
msgid "Storage Group %s is not found."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1898
#, python-format
msgid ""
"Invalid iSCSI port %(sp)s-%(port)s-%(vlan)s found in io_port_list, will "
"be ignored."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1967
#, python-format
msgid "See unavailable iSCSI target: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2194
msgid ""
"destroy_empty_storage_group: True. Empty storage group will be deleted "
"after volume is detached."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2227
msgid "force_delete_lun_in_storagegroup=True"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2234
msgid ""
"ignore_pool_full_threshold: True. LUN creation will still be forced even "
"if the pool full threshold is exceeded."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2254
#, python-format
msgid ""
"The following specified storage pools do not exist: %(unexist)s. This "
"host will only manage the storage pools: %(exist)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2383
msgid "snapcopy metadata is ignored when creating volume."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2426
msgid "Unknown migration rate specified, using [high] as migration rate."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2434
msgid ""
"Extra spec key 'storagetype:pool' is obsoleted since driver version "
"5.1.0. This key will be ignored."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2471
msgid ""
"Both 'storagetype:prvosioning' and 'provisioning:type' are set in the "
"extra specs, the value of 'provisioning:type' will be used. The key "
"'storagetype:provisioning' may be deprecated in the next release."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2480
msgid ""
"Extra spec key 'storagetype:provisioning' may be deprecated in the next "
"release. It is recommended to use extra spec key 'provisioning:type' "
"instead."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2533
#, python-format
msgid ""
"LUN corresponding to %s is still in some Storage Groups.Try to bring the "
"LUN out of Storage Groups and retry the deletion."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2566
#, python-format
msgid "LUN %(name)s is not ready for extension: %(out)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2587
msgid ""
"Failed to get target_pool_name and target_array_serial. 'location_info' "
"is not in host['capabilities']."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2600
msgid "Error on parsing target_pool_name/target_array_serial."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2614
#, python-format
msgid ""
"Didn't get the pool information of the host %s. Storage assisted "
"Migration is not supported. The host may be using a legacy driver."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2749
#: cinder/volume/drivers/huawei/huawei_driver.py:872
msgid "Storage-assisted migration failed during retype."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2822
#, python-format
msgid "Storage Pool '%(pool)s' is '%(state)s'."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2832
#, python-format
msgid ""
"Maximum number of Pool LUNs, %s, have been created. No more LUN creation "
"can be done."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2939
#, python-format
msgid "LUN %(name)s is not ready for snapshot: %(out)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3261
#, python-format
msgid "LUN with id %(remove_id)s is not present in cg %(cg_name)s, skip it."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3356
#, python-format
msgid "Storage Group %s is not found. Create it."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3419
#, python-format
msgid "Failed to register %(itor)s to SP%(sp)s port %(portid)s because: %(msg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3538
#, python-format
msgid "Failed to extract initiators of %s, so ignore deregistration operation."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3545
#, python-format
msgid "Failed to deregister %(itor)s because: %(msg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3806
#, python-format
msgid "Storage Group %s is not found. terminate_connection() is unnecessary."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3815
#, python-format
msgid "Volume %(vol)s was not in Storage Group %(sg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3837
#, python-format
msgid "Failed to destroy Storage Group %s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:3843
#, python-format
msgid "Fail to connect host %(host)s back to storage group %(sg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:4219
#, python-format
msgid "No replication info from this volume: %s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:4319
#, python-format
msgid ""
"Delete the temporary cgsnapshot %(name)s failed. This temporary "
"cgsnapshot can be deleted manually. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:4406
#, python-format
msgid ""
"The source volume is a legacy volume. Create volume in the pool where the"
" source volume %s is created."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:4482
#, python-format
msgid "CreateSMPTask.revert: delete mount point %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:4502
#, python-format
msgid "AttachSnapTask.revert: detach mount point %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:4540
#, python-format
msgid "CreateDestLunTask.revert: delete temp lun %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:4609
#, python-format
msgid "CreateSnapshotTask.revert: delete temp cgsnapshot %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:4614
#, python-format
msgid "CreateSnapshotTask.revert: delete temp snapshot %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:4636
#, python-format
msgid ""
"CopySnapshotTask.revert: delete the copied snapshot %(new_name)s of "
"%(source_name)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:4757
#, python-format
msgid "MirrorView already created, mirror name %(name)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:4791
#, python-format
msgid "MirrorView %(name)s was already deleted. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:4868
#, python-format
msgid "Getting MirrorView %(name)s failed. Message: %(msg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:4988
#, python-format
msgid "%(method)s: destroying mirror view %(name)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:5021
#, python-format
msgid "%(method)s: destroying secondary LUN %(name)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:5047
#, python-format
msgid "%(method)s: removing secondary image from %(name)s."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:131
msgid "No storage pool name or id was found."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:170
msgid "No protection domain name or id was specified in configuration."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:191
msgid "Verify certificate is not set, using default of False."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:239
msgid "QoS specs are overriding extra_specs."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:567
#, python-format
msgid ""
"ScaleIO only supports volumes with a granularity of 8 GBs. The new volume"
" size is: %d."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:658
#, python-format
msgid "Ignoring error in delete volume %s: Volume not found."
msgstr ""

#: cinder/volume/drivers/emc/scaleio.py:662
msgid ""
"Volume does not have provider_id thus does not map to a ScaleIO volume. "
"Allowing deletion to proceed."
msgstr ""

#: cinder/volume/drivers/emc/xtremio.py:158
#, python-format
msgid "object %(key)s of type %(typ)s not found, %(err_msg)s"
msgstr ""

#: cinder/volume/drivers/emc/xtremio.py:578
msgid "terminate_connection: lun map not found"
msgstr ""

#: cinder/volume/drivers/fujitsu/eternus_dx_common.py:230
#, python-format
msgid "create_volume, volumename: %(volumename)s, Element Name is in use."
msgstr ""

#: cinder/volume/drivers/fujitsu/eternus_dx_common.py:899
#, python-format
msgid ""
"update_volume_stats, eternus_pool:%(eternus_pool)s, specified pool is not"
" found."
msgstr ""

#: cinder/volume/drivers/fujitsu/eternus_dx_common.py:1724
#, python-format
msgid ""
"_map_lun, lun_name: %(volume_uid)s, Initiator: %(initiator)s, target: "
"%(target)s, Return code: %(rc)lu, Error: %(errordesc)s."
msgstr ""

#: cinder/volume/drivers/fujitsu/eternus_dx_common.py:1757
#, python-format
msgid ""
"_map_lun, lun_name: %(volume_uid)s, Initiator: %(initiator)s, ag: %(ag)s,"
" Return code: %(rc)lu, Error: %(errordesc)s."
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_common.py:410
#: cinder/volume/drivers/hitachi/hbsd_common.py:416
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1342
#, python-format
msgid "Failed to restart horcm: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_fc.py:181
#, python-format
msgid "Failed to add host group: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_horcm.py:851
#, python-format
msgid "Failed to discard zero page: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1320
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1329
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1336
#: cinder/volume/drivers/hitachi/hbsd_horcm.py:1360
#, python-format
msgid "Failed to create pair: %s"
msgstr ""

#: cinder/volume/drivers/hitachi/hbsd_snm2.py:145
#, python-format
msgid "ldev(%(ldev)d) is already mapped (hlun: %(hlu)d)"
msgstr ""

#: cinder/volume/drivers/hitachi/hnas_backend.py:273
#, python-format
msgid "get_evs: %(out)s -- No find for %(fsid)s"
msgstr ""

#: cinder/volume/drivers/hitachi/hnas_backend.py:308
#, python-format
msgid "get_fsid: %(out)s -- No info for %(fslabel)s"
msgstr ""

#: cinder/volume/drivers/hitachi/hnas_iscsi.py:739
msgid "terminate_conn: provider location empty."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_common.py:444
#, python-format
msgid ""
"srstatld requires WSAPI version '%(srstatld_version)s' version "
"'%(version)s' is installed."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_common.py:569
#, python-format
msgid "Virtual Volume Set '%s' doesn't exist on array."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_common.py:681
#: cinder/volume/drivers/hpe/hpe_3par_common.py:2527
#, python-format
msgid "Delete Snapshot id not found. Removing from cinder: %(id)s Ex: %(msg)s"
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_common.py:782
#: cinder/volume/drivers/hpe/hpe_lefthand_iscsi.py:1148
#, python-format
msgid "Failed to manage virtual volume %(disp)s due to error during retype."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_common.py:1419
#, python-format
msgid "3PAR vlun for volume %(name)s not found on host %(host)s"
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_common.py:1710
msgid ""
"'hpe3par:cpg' is not supported as an extra spec in a volume type.  CPG's "
"are chosen by the cinder scheduler, as a pool, from the cinder.conf entry"
" 'hpe3par_cpg', which can be a list of CPGs."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_common.py:2139
#, python-format
msgid "Delete volume id not found. Removing from cinder: %(id)s Ex: %(msg)s"
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_common.py:2321
#, python-format
msgid "Issue occurred in clear_volume_key_value_pair: %s"
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_common.py:3092
#: cinder/volume/drivers/hpe/hpe_lefthand_iscsi.py:1538
#, python-format
msgid ""
"The secondary array must have an API version of %(min_ver)s or higher. "
"Array '%(target)s' is on %(target_ver)s, therefore it will not be added "
"as a valid replication target."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_common.py:3102
#, python-format
msgid ""
"'%s' is not a valid replication array. In order to be valid, backend_id, "
"replication_mode, hpe3par_api_url, hpe3par_username, hpe3par_password, "
"cpg_map, san_ip, san_login, and san_password must be specified. If the "
"target is managed, managed_backend_name must be set as well."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_fc.py:128
#: cinder/volume/drivers/hpe/hpe_3par_iscsi.py:140
msgid ""
"The primary array is not reachable at this time. Since replication is "
"enabled, listing replication targets and failing over a volume can still "
"be performed."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_iscsi.py:209
#, python-format
msgid "Invalid IP address format '%s'"
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_iscsi.py:241
#, python-format
msgid ""
"Found invalid iSCSI IP address(s) in configuration option(s) "
"hpe3par_iscsi_ips or iscsi_ip_address '%s.'"
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_iscsi.py:392
#, python-format
msgid ""
"iSCSI IP: '%s' was not found in hpe3par_iscsi_ips list defined in "
"cinder.conf."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_iscsi.py:430
msgid "Least busy iSCSI port not found, using first iSCSI port in list."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_iscsi.py:583
msgid ""
"Host exists without CHAP credentials set and has iSCSI attachments but "
"CHAP is enabled. Updating host with new CHAP credentials."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_iscsi.py:615
msgid "Host has no CHAP key, but CHAP is enabled."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_iscsi.py:619
msgid "No host or VLUNs exist. Generating new CHAP key."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_iscsi.py:648
msgid "Non-iSCSI VLUN detected."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_3par_iscsi.py:652
msgid "No VLUN contained CHAP credentials. Generating new CHAP key."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_lefthand_iscsi.py:347
#, python-format
msgid ""
"HPELeftHand API is version %(current)s. A minimum version of %(min)s is "
"needed for manage/unmanage support."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_lefthand_iscsi.py:822
msgid "The 'hplh' prefix is deprecated. Use 'hpelh' instead."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_lefthand_iscsi.py:862
#, python-format
msgid "CHAP secret exists for host %s but CHAP is disabled"
msgstr ""

#: cinder/volume/drivers/hpe/hpe_lefthand_iscsi.py:865
#, python-format
msgid "CHAP is enabled, but server secret not configured on server %s"
msgstr ""

#: cinder/volume/drivers/hpe/hpe_lefthand_iscsi.py:939
#, python-format
msgid "%s"
msgstr ""

#: cinder/volume/drivers/hpe/hpe_lefthand_iscsi.py:1439
msgid ""
"The primary array is currently offline, remote copy has been "
"automatically paused."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_lefthand_iscsi.py:1548
#, python-format
msgid ""
"'%s' is not a valid replication array. In order to be valid, backend_id, "
"hpelefthand_api_url, hpelefthand_username, hpelefthand_password, and "
"hpelefthand_clustername, must be specified. If the target is managed, "
"managed_backend_name must be set as well."
msgstr ""

#: cinder/volume/drivers/hpe/hpe_lefthand_iscsi.py:1661
#, python-format
msgid ""
"There was a problem when trying to determine if the volume can be failed-"
"back: %s"
msgstr ""

#: cinder/volume/drivers/hpe/hpe_lefthand_iscsi.py:1766
#: cinder/volume/drivers/hpe/hpe_lefthand_iscsi.py:1787
#: cinder/volume/drivers/hpe/hpe_lefthand_iscsi.py:1809
#, python-format
msgid ""
"There was no extra_spec value for %(spec_name)s, so the default value of "
"%(def_val)s will be used. To overwrite this, set this value in the volume"
" type extra_specs."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:710
#, python-format
msgid "Failure deleting the snapshot %(snapshot_id)s of volume %(volume_id)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:837
msgid "Can't find snapshot on the array."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:1196
msgid "No license for SplitMirror."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:1222
msgid "No license for migration."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:1364
#, python-format
msgid "Rename lun %(lun_id)s fails when unmanaging volume %(volume)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:1459
#, python-format
msgid "Can't find snapshot on the array: %s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:1470
#, python-format
msgid ""
"Failed to rename snapshot %(snapshot_id)s, snapshot name on array is "
"%(snapshot_name)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:1734
#: cinder/volume/drivers/huawei/huawei_driver.py:1977
#, python-format
msgid "LUN is not in lungroup. LUN ID: %(lun_id)s. Lungroup id: %(lungroup_id)s."
msgstr ""

#: cinder/volume/drivers/huawei/huawei_driver.py:1984
msgid "Can't find lun on the array."
msgstr ""

#: cinder/volume/drivers/huawei/hypermetro.py:227
#, python-format
msgid "Lun is not in lungroup. Lun id: %(lun_id)s, lungroup id: %(lungroup_id)s"
msgstr ""

#: cinder/volume/drivers/huawei/replication.py:197
#, python-format
msgid "Split replication exception: %s."
msgstr ""

#: cinder/volume/drivers/huawei/replication.py:346
#, python-format
msgid "Get remote array wwn failed. Error: %s."
msgstr ""

#: cinder/volume/drivers/huawei/replication.py:354
#, python-format
msgid "Get remote devices failed. Error: %s."
msgstr ""

#: cinder/volume/drivers/huawei/replication.py:383
msgid "Remote device is unavailable."
msgstr ""

#: cinder/volume/drivers/huawei/replication.py:561
#: cinder/volume/drivers/huawei/replication.py:611
#, python-format
msgid "No pair id in volume %s."
msgstr ""

#: cinder/volume/drivers/huawei/replication.py:568
#: cinder/volume/drivers/huawei/replication.py:618
#, python-format
msgid "No remote lun id in volume %s."
msgstr ""

#: cinder/volume/drivers/huawei/rest_client.py:147
#, python-format
msgid "Login failed. Error: %s."
msgstr ""

#: cinder/volume/drivers/huawei/rest_client.py:1265
#: cinder/volume/drivers/huawei/rest_client.py:1277
msgid "Can't find target iqn from rest."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_common.py:320
#, python-format
msgid "warning: Tried to delete vdisk %s but it does not exist."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_common.py:357
#, python-format
msgid "Failed to run command: %s."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_common.py:761
msgid "_remove_device: invalid properties or device."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_common.py:814
#, python-format
msgid ""
"_unmap_vdisk_from_host: No mapping of volume %(vol_name)s to any host "
"found."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_common.py:820
#, python-format
msgid ""
"_unmap_vdisk_from_host: Multiple mappings of volume %(vdisk_name)s found,"
" no host specified."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_fc.py:160
#, python-format
msgid "Host %(host)s was not found on backend storage."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem_iscsi.py:191
#, python-format
msgid "_get_vdisk_map_properties: Did not find a preferred node for vdisk %s."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/storwize_svc_common.py:570
#, python-format
msgid "Failed to run lsguicapability. Exception: %s."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/storwize_svc_common.py:869
#, python-format
msgid "unmap_vol_from_host: No mapping of volume %(vol_name)s to any host found."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/storwize_svc_common.py:875
#, python-format
msgid ""
"unmap_vol_from_host: Multiple mappings of volume %(vol_name)s found, no "
"host specified."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/storwize_svc_common.py:887
#, python-format
msgid ""
"unmap_vol_from_host: No mapping of volume %(vol_name)s to host %(host)s "
"found."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/storwize_svc_common.py:2027
msgid ""
"Unable to use san_ip to create SSHPool. Now attempting to use "
"storwize_san_secondary_ip to create SSHPool."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/storwize_svc_common.py:2034
msgid ""
"Unable to create SSHPool using san_ip and not able to use "
"storwize_san_secondary_ip since it is not configured."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/storwize_svc_common.py:2050
#, python-format
msgid ""
"Unable to execute SSH command with storwize_san_secondary_ip. Attempting "
"to switch IP back to san_ip %s."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/storwize_svc_common.py:2060
#, python-format
msgid "Unable to execute SSH command. Attempting to switch IP to %s."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/storwize_svc_common.py:2068
msgid ""
"Unable to execute SSH command. Not able to use storwize_san_secondary_ip "
"since it is not configured."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/storwize_svc_common.py:2443
#, python-format
msgid "Volume %s does not exist."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/storwize_svc_fc.py:179
#: cinder/volume/drivers/ibm/storwize_svc/storwize_svc_iscsi.py:187
#, python-format
msgid "initialize_connection: Did not find a preferred node for volume %s."
msgstr ""

#: cinder/volume/drivers/ibm/storwize_svc/storwize_svc_iscsi.py:142
msgid "CHAP secret exists for host but CHAP is disabled."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:90
msgid "The MCS Channel is grouped."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:94
msgid "No mapping."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:102
msgid "IQN already existed."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:107
msgid "IQN has been used to create map."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:108
msgid "No such host alias name."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:844
#, python-format
msgid "Volume %(volume_id)s already deleted."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:855
#, python-format
msgid "Volume still %(status)s Cannot delete volume."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1160
msgid "Failed to get Raid Snapshot ID and did not store in snapshot."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1173
#, python-format
msgid "Snapshot still %(status)s Cannot delete snapshot."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1633
msgid "Failed to get target pool id."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1870
#, python-format
msgid "Volume %(volume_id)s cannot be retyped during attachment."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1877
#, python-format
msgid "Volume %(volume_id)s cannot be retyped because it has snapshot."
msgstr ""

#: cinder/volume/drivers/infortrend/eonstor_ds_cli/common_cli.py:1900
#, python-format
msgid "The provisioning: %(provisioning)s is not valid."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:70
msgid ""
"It is not the recommended way to use drivers by NetApp. Please use "
"NetAppDriver to achieve the functionality."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:145
#, python-format
msgid "Extra spec %(old)s is obsolete.  Use %(new)s instead."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:150
#, python-format
msgid "Extra spec %(old)s is deprecated.  Use %(new)s instead."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:143
#, python-format
msgid "Could not determine root volume name on %s."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:338
msgid ""
"The option 'netapp_volume_list' is deprecated and will be removed in the "
"future releases. Please use the option 'netapp_pool_name_search_pattern' "
"instead."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:384
msgid "Volume refresh job already running. Returning..."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:392
#, python-format
msgid "Error refreshing volume info. Message: %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_base.py:246
#, python-format
msgid "No entry in LUN table for volume/snapshot %(name)s."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_base.py:371
#, python-format
msgid ""
"LUN misalignment may occur for current initiator group %(ig_nm)s) with "
"host OS type %(ig_os)s. Please configure initiator group manually "
"according to the type of the host OS."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:325
#, python-format
msgid ""
"Exception while registering image %(image_id)s in cache. Exception: "
"%(exc)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:394
#, python-format
msgid "Exception during cache cleaning %(share)s. Message - %(ex)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:605
msgid "Discover file retries exhausted."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:663
msgid "Unexpected exception while short listing used share."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:773
#, python-format
msgid "Exception moving file %(src)s. Message - %(e)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_cmode.py:244
msgid "No shares found hence skipping ssc refresh."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:524
msgid "ssc job in progress. Returning... "
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:536
msgid "refresh stale ssc job in progress. Returning... "
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:641
#, python-format
msgid ""
"The user does not have access or sufficient privileges to use all netapp "
"APIs. The following extra_specs will fail or be ignored: %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_7mode.py:179
#, python-format
msgid "Error finding LUNs for volume %s. Verify volume exists."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:138
#, python-format
msgid "Error mapping LUN. Code :%(code)s, Message: %(message)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:151
#, python-format
msgid "Error unmapping LUN. Code :%(code)s, Message: %(message)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:397
#, python-format
msgid "Failed to invoke ems. Message : %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_cmode.py:486
#, python-format
msgid "Rename failure in cleanup of cDOT QOS policy group %(name)s: %(ex)s"
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:219
#, python-format
msgid ""
"Production use of \"%(backend)s\" backend requires the Cinder controller "
"to have multipathing properly set up and the configuration option "
"\"%(mpflag)s\" to be set to \"True\"."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:664
#, python-format
msgid "Snapshot volume creation failed for snapshot %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:708
#, python-format
msgid "Failure deleting job %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:711
#, python-format
msgid "Volume copy job for src vol %s not found."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:728
#, python-format
msgid "Failure deleting temp snapshot %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:737
#, python-format
msgid "Volume %s already deleted."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:972
#, python-format
msgid "Snapshot %s already deleted."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:1033
#: cinder/volume/drivers/netapp/eseries/library.py:1062
#, python-format
msgid "Unable to remove snapshot group - %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:1351
#, python-format
msgid "Unable to update host type for host with label %(l)s. %(e)s"
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:1356
#, python-format
msgid "Message - %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:1654
msgid ""
"The option 'netapp_storage_pools' is deprecated and will be removed in "
"the future releases. Please use the option "
"'netapp_pool_name_search_pattern' instead."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:1692
#, python-format
msgid "No storage pool found with available capacity %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:1953
msgid "Consistency group already deleted."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:1960
msgid "Unable to remove CG from the deletion map."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/library.py:2041
msgid "Returning as clean tmp vol job already running."
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:255
#, python-format
msgid "Cannot delete snapshot %(origin)s: %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:284
#: cinder/volume/drivers/nexenta/nfs.py:427
#: cinder/volume/drivers/nexenta/ns5/nfs.py:325
#, python-format
msgid "Failed to delete zfs snapshot %(volume_name)s@%(name)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:344
#: cinder/volume/drivers/nexenta/nfs.py:164
#, python-format
msgid "Remote NexentaStor appliance at %s should be SSH-bound."
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:364
#: cinder/volume/drivers/nexenta/nfs.py:184
#, python-format
msgid ""
"Cannot send source snapshot %(src)s to destination %(dst)s. Reason: "
"%(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:372
#: cinder/volume/drivers/nexenta/nfs.py:192
#, python-format
msgid ""
"Cannot delete temporary source snapshot %(src)s on NexentaStor Appliance:"
" %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:378
#: cinder/volume/drivers/nexenta/nfs.py:198
#, python-format
msgid "Cannot delete source volume %(volume)s on NexentaStor Appliance: %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:388
#: cinder/volume/drivers/nexenta/nfs.py:208
#, python-format
msgid ""
"Cannot delete temporary destination snapshot %(dst)s on NexentaStor "
"Appliance: %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:424
#: cinder/volume/drivers/nexenta/nfs.py:266
#, python-format
msgid "Cannot retype from %(src_backend)s to %(dst_backend)s."
msgstr ""

#: cinder/volume/drivers/nexenta/nfs.py:137
#, python-format
msgid "Volume status must be 'available' or 'retyping'. Current volume status: %s"
msgstr ""

#: cinder/volume/drivers/nexenta/nfs.py:142
msgid "Unsupported host. No capabilities found"
msgstr ""

#: cinder/volume/drivers/nexenta/nfs.py:358
#: cinder/volume/drivers/nexenta/ns5/nfs.py:182
#, python-format
msgid "Cannot destroy created folder: %(vol)s/%(folder)s"
msgstr ""

#: cinder/volume/drivers/nexenta/nfs.py:388
#, python-format
msgid "Cannot destroy cloned folder: %(vol)s/%(folder)s"
msgstr ""

#: cinder/volume/drivers/nexenta/nfs.py:652
#, python-format
msgid "Share %s ignored due to invalid format. Must be of form address:/export."
msgstr ""

#: cinder/volume/drivers/nexenta/nfs.py:703
#, python-format
msgid "Mount attempt %(attempt)d failed: %(error)s. Retrying mount ..."
msgstr ""

#: cinder/volume/drivers/nexenta/ns5/iscsi.py:226
#, python-format
msgid ""
"Got error trying to delete volume %(volume)s, assuming it is already "
"gone: %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/ns5/iscsi.py:287
#: cinder/volume/drivers/nexenta/ns5/nfs.py:259
#, python-format
msgid "Could not delete snapshot %s - it has dependencies"
msgstr ""

#: cinder/volume/drivers/nexenta/ns5/iscsi.py:350
#, python-format
msgid "Failed to delete zfs snapshot %s"
msgstr ""

#: cinder/volume/drivers/nexenta/ns5/nfs.py:298
#, python-format
msgid "Cannot destroy cloned filesystem: %(vol)s/%(filesystem)s"
msgstr ""

#: cinder/volume/drivers/prophetstor/dpl_iscsi.py:153
#, python-format
msgid "Cannot get volume status %(exc)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1254
#, python-format
msgid "Flexvisor failed to delete volume %(id)s from the group %(vgid)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1259
#, python-format
msgid ""
"Flexvisor failed to delete volume %(id)s from group %(vgid)s due to "
"%(status)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1428
#, python-format
msgid "Failed to query pool %(id)s status %(ret)d."
msgstr ""

#: cinder/volume/drivers/vmware/datastore.py:227
#, python-format
msgid "Unable to fetch datastores connected to host %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:534
#, python-format
msgid "Trying to boot from an empty volume: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:717
#, python-format
msgid "Error occurred while deleting temporary disk: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:849
#, python-format
msgid "Error occurred while deleting descriptor: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:882
#, python-format
msgid "Error occurred while deleting backing: %s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1228
#, python-format
msgid "Volume: %s is in use, can't retype."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1297
#, python-format
msgid ""
"There are no datastores matching new requirements; can't retype volume: "
"%s."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1351
#, python-format
msgid ""
"Changing backing: %(backing)s name from %(new_name)s to %(old_name)s "
"failed."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1401
#, python-format
msgid ""
"Unable to extend volume: %(vol)s to size: %(size)s on current datastore "
"due to insufficient space."
msgstr ""

#: cinder/volume/drivers/vmware/vmdk.py:1610
#, python-format
msgid ""
"Cannot undo volume rename; old name was %(old_name)s and new name is "
"%(new_name)s."
msgstr ""

#: cinder/volume/drivers/zfssa/zfssaiscsi.py:192
msgid "zfssa_initiator_config not found. Using deprecated configuration options."
msgstr ""

#: cinder/volume/drivers/zfssa/zfssaiscsi.py:206
#, python-format
msgid ""
"zfssa_initiator: %(ini)s wont be used on zfssa_initiator_group= "
"%(inigrp)s."
msgstr ""

#: cinder/volume/drivers/zfssa/zfssaiscsi.py:1017
#, python-format
msgid "Volume %s exists but can't be deleted"
msgstr ""

#: cinder/volume/drivers/zfssa/zfssarest.py:998
#, python-format
msgid "Property %s already exists."
msgstr ""

#: cinder/volume/flows/api/create_volume.py:254
#, python-format
msgid ""
"Failed to retrieve volume_type from image metadata. '%(img_vol_type)s' "
"doesn't match any volume types."
msgstr ""

#: cinder/volume/flows/api/create_volume.py:330
#, python-format
msgid ""
"Availability zone '%(s_az)s' not found, falling back to "
"'%(s_fallback_az)s'."
msgstr ""

#: cinder/volume/flows/api/create_volume.py:392
msgid "Volume type will be changed to be the same as the source volume."
msgstr ""

#: cinder/volume/flows/api/create_volume.py:635
#, python-format
msgid ""
"Quota %(s_name)s exceeded for %(s_pid)s, tried to create volume "
"(%(d_consumed)d volume(s) already consumed)."
msgstr ""

#: cinder/volume/flows/manager/create_volume.py:685
#, python-format
msgid ""
"Failed to create volume from image-volume cache, will fall back to "
"default behavior. Error: %(exception)s"
msgstr ""

#: cinder/volume/targets/cxt.py:131 cinder/volume/targets/tgt.py:166
#, python-format
msgid "Persistence file already exists for volume, found file at: %s"
msgstr ""

#: cinder/volume/targets/cxt.py:194 cinder/volume/targets/tgt.py:255
#, python-format
msgid "Volume path %s does not exist, nothing to remove."
msgstr ""

#: cinder/volume/targets/iet.py:191
#, python-format
msgid ""
"Failed to update %(conf)s for volume id %(vol_id)s after removing iscsi "
"target. %(conf)s does not exist."
msgstr ""

#: cinder/volume/targets/lio.py:86
#, python-format
msgid ""
"Failed to save iscsi LIO configuration when modifying volume id: "
"%(vol_id)s."
msgstr ""

#: cinder/volume/targets/lio.py:97
msgid "Failed to restore iscsi LIO configuration."
msgstr ""

#: cinder/volume/targets/tgt.py:84
msgid "Attempting recreate of backing lun..."
msgstr ""

#: cinder/volume/targets/tgt.py:192
#, python-format
msgid "Could not create target because it already exists for volume: %s"
msgstr ""

#: cinder/volume/targets/tgt.py:277
#, python-format
msgid ""
"Failed target removal because target or ACL's couldn't be found for iqn: "
"%s."
msgstr ""

#: cinder/volume/targets/tgt.py:296
msgid "Silent failure of target removal detected, retry...."
msgstr ""

#: cinder/zonemanager/utils.py:77
msgid "Driver didn't return connection info, can't add zone."
msgstr ""

#: cinder/zonemanager/utils.py:101
msgid "Driver didn't return connection info from terminate_connection call."
msgstr ""

#: cinder/zonemanager/drivers/brocade/brcd_fc_zone_driver.py:317
#, python-format
msgid "Zoning policy not recognized: %(policy)s"
msgstr ""

#: cinder/zonemanager/drivers/cisco/cisco_fc_zone_client_cli.py:394
#, python-format
msgid "Error running SSH command: %s"
msgstr ""

